const json = (data, status = 200, extraHeaders = {}) => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', ...extraHeaders }});
const now = () => Math.floor(Date.now()/1000);
const ADMIN_EMAIL = 'Varejaoeverton@gmail.com';

function getIp(req){return req.headers.get('cf-connecting-ip') || req.headers.get('x-forwarded-for') || '0.0.0.0'}
function getUa(req){return req.headers.get('user-agent') || ''}
async function body(req){ try { return await req.json(); } catch { return {}; } }
function b64url(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(str){str=str.replace(/-/g,'+').replace(/_/g,'/'); while(str.length%4) str+='='; return Uint8Array.from(atob(str), c=>c.charCodeAt(0))}
async function sha256(text){return b64url(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)))}
async function hmac(data, secret){const key=await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), {name:'HMAC', hash:'SHA-256'}, false, ['sign']); return b64url(await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(data)))}
async function signJwt(payload, secret){const header=b64url(new TextEncoder().encode(JSON.stringify({alg:'HS256',typ:'JWT'}))); const p=b64url(new TextEncoder().encode(JSON.stringify(payload))); const s=await hmac(`${header}.${p}`, secret); return `${header}.${p}.${s}`}
async function verifyJwt(token, secret){try{const [h,p,s]=token.split('.'); if(!h||!p||!s)return null; const expected=await hmac(`${h}.${p}`, secret); if(expected!==s)return null; const payload=JSON.parse(new TextDecoder().decode(fromB64url(p))); if(payload.exp && payload.exp < now()) return null; return payload;}catch{return null}}
async function hashPassword(password){const salt=crypto.getRandomValues(new Uint8Array(16)); const key=await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2', salt, iterations:120000, hash:'SHA-256'}, key, 256); return `pbkdf2$120000$${b64url(salt)}$${b64url(bits)}`}
async function verifyPassword(password, stored){try{const [algo,iters,saltB64,hashB64]=stored.split('$'); const salt=fromB64url(saltB64); const key=await crypto.subtle.importKey('raw', new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2', salt, iterations:Number(iters), hash:'SHA-256'}, key, 256); return b64url(bits)===hashB64;}catch{return false}}
function strongPassword(p){return typeof p==='string' && p.length>=8 && /[A-Z]/.test(p) && /[a-z]/.test(p) && /\d/.test(p) && /[^A-Za-z0-9]/.test(p)}
function slugify(s){return String(s||'pagina').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'pagina'}
async function log(env, req, data){try{await env.DB.prepare('INSERT INTO security_logs (user_id,email,action,status,ip,user_agent,details) VALUES (?,?,?,?,?,?,?)').bind(data.user_id||null,data.email||null,data.action,data.status,getIp(req),getUa(req),data.details||'').run()}catch{}}
async function rateLimit(env, req, key, limit=30, window=60){ if(!env.DB) return true; const ip=getIp(req); const marker=`rl:${key}:${ip}:${Math.floor(now()/window)}`; try{ const row=await env.DB.prepare('SELECT value FROM settings WHERE key=?').bind(marker).first(); const count=row?Number(row.value):0; if(count>=limit) return false; await env.DB.prepare('INSERT OR REPLACE INTO settings(key,value,private,updated_at) VALUES(?,?,1,?)').bind(marker,String(count+1),now()).run(); return true;}catch{return true}}
async function requireUser(req, env){const auth=req.headers.get('authorization')||''; const token=auth.startsWith('Bearer ')?auth.slice(7):null; if(!token || !env.JWT_SECRET) return null; const payload=await verifyJwt(token, env.JWT_SECRET); if(!payload) return null; const u=await env.DB.prepare('SELECT id,name,email,role,plan_id,status FROM users WHERE id=?').bind(payload.sub).first(); return u && u.status==='active'?u:null}
async function requireAdmin(req, env){const u=await requireUser(req, env); return u && u.role==='admin'?u:null}
async function seedAdmin(env){ const pass=env.ADMIN_PASSWORD; if(!pass) return; const existing=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(ADMIN_EMAIL.toLowerCase()).first(); if(!existing){ const hash=await hashPassword(pass); await env.DB.prepare('INSERT INTO users(name,email,password_hash,role,status,email_verified) VALUES(?,?,?,?,?,1)').bind('Administrador', ADMIN_EMAIL.toLowerCase(), hash, 'admin', 'active').run(); }}

async function register(req, env){ if(!await rateLimit(env, req, 'register', 10, 300)) return json({ok:false,error:'Muitas tentativas. Aguarde alguns minutos.'},429); const b=await body(req); const name=String(b.name||'').trim(); const email=String(b.email||'').trim().toLowerCase(); const phone=String(b.phone||'').trim(); const password=String(b.password||''); if(name.length<2) return json({ok:false,error:'Informe seu nome.'},400); if(!/^\S+@\S+\.\S+$/.test(email)) return json({ok:false,error:'E-mail inválido.'},400); if(!strongPassword(password)) return json({ok:false,error:'A senha precisa ter 8+ caracteres, maiúscula, minúscula, número e símbolo.'},400); const exists=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first(); if(exists) return json({ok:false,error:'Este e-mail já está cadastrado.'},409); const hash=await hashPassword(password); const token=b64url(crypto.getRandomValues(new Uint8Array(32))); await env.DB.prepare('INSERT INTO users(name,email,phone,password_hash,email_token) VALUES(?,?,?,?,?)').bind(name,email,phone,hash,token).run(); await log(env, req, {email, action:'register', status:'success'}); return json({ok:true,message:'Conta criada com sucesso. Faça login para continuar.'}); }
async function login(req, env){ await seedAdmin(env); if(!await rateLimit(env, req, 'login', 15, 300)) return json({ok:false,error:'Muitas tentativas de login.'},429); const b=await body(req); const email=String(b.email||'').trim().toLowerCase(); const password=String(b.password||''); const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first(); if(!u || !await verifyPassword(password,u.password_hash)){ await log(env, req, {email, action:'login', status:'failed'}); return json({ok:false,error:'E-mail ou senha inválidos.'},401); } if(u.status!=='active') return json({ok:false,error:'Conta bloqueada. Fale com o suporte.'},403); const token=await signJwt({sub:u.id,role:u.role,email:u.email,exp:now()+86400*7}, env.JWT_SECRET || 'dev-secret-change'); await log(env, req, {user_id:u.id,email, action:'login', status:'success'}); return json({ok:true,token,user:{id:u.id,name:u.name,email:u.email,role:u.role,plan_id:u.plan_id}}); }
async function me(req, env){ const u=await requireUser(req, env); if(!u) return json({ok:false,error:'Não autenticado.'},401); return json({ok:true,user:u}); }
async function forgot(req, env){ const b=await body(req); const email=String(b.email||'').trim().toLowerCase(); const u=await env.DB.prepare('SELECT id,name,email FROM users WHERE email=?').bind(email).first(); if(!u) return json({ok:true,message:'Se o e-mail existir, enviaremos um link de redefinição.'}); const raw=b64url(crypto.getRandomValues(new Uint8Array(32))); const tokenHash=await sha256(raw); await env.DB.prepare('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES(?,?,?)').bind(u.id, tokenHash, now()+3600).run(); const base=env.PUBLIC_BASE_URL || new URL(req.url).origin; const link=`${base}/?reset=${encodeURIComponent(raw)}&email=${encodeURIComponent(email)}`; if(env.RESEND_API_KEY){ await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.MAIL_FROM||'LumaPage <noreply@lumapage.ai>',to:email,subject:'Redefinir sua senha - LumaPage AI',html:`<p>Olá ${u.name}, clique para redefinir sua senha:</p><p><a href="${link}">${link}</a></p><p>Este link expira em 1 hora.</p>`})}); return json({ok:true,message:'Enviamos o link de redefinição para seu e-mail.'}); }
 return json({ok:true,message:'Link gerado. Configure RESEND_API_KEY para envio real.',dev_link:link}); }
async function resetPassword(req, env){ const b=await body(req); const email=String(b.email||'').trim().toLowerCase(); const token=String(b.token||''); const password=String(b.password||''); if(!strongPassword(password)) return json({ok:false,error:'Senha fraca.'},400); const u=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first(); if(!u) return json({ok:false,error:'Token inválido.'},400); const h=await sha256(token); const r=await env.DB.prepare('SELECT * FROM password_resets WHERE user_id=? AND token_hash=? AND used=0 AND expires_at>? ORDER BY id DESC').bind(u.id,h,now()).first(); if(!r) return json({ok:false,error:'Token inválido ou expirado.'},400); const ph=await hashPassword(password); await env.DB.prepare('UPDATE users SET password_hash=?, updated_at=? WHERE id=?').bind(ph,now(),u.id).run(); await env.DB.prepare('UPDATE password_resets SET used=1 WHERE id=?').bind(r.id).run(); return json({ok:true,message:'Senha alterada com sucesso.'}); }
async function plans(env){ const rows=await env.DB.prepare('SELECT * FROM plans WHERE active=1 ORDER BY price ASC').all(); return json({ok:true,plans:rows.results||[]}); }
async function dashboard(req, env){ const u=await requireUser(req, env); if(!u) return json({ok:false,error:'Não autenticado.'},401); const projects=await env.DB.prepare('SELECT * FROM projects WHERE user_id=? ORDER BY id DESC').bind(u.id).all(); const payments=await env.DB.prepare('SELECT * FROM payments WHERE user_id=? ORDER BY id DESC LIMIT 10').bind(u.id).all(); return json({ok:true,projects:projects.results||[],payments:payments.results||[],stats:{pages:(projects.results||[]).length,visits:(projects.results||[]).reduce((a,p)=>a+(p.visits||0),0),clicks:(projects.results||[]).reduce((a,p)=>a+(p.whatsapp_clicks||0),0)}}); }
async function aiGenerate(req, env){ const u=await requireUser(req, env); if(!u) return json({ok:false,error:'Não autenticado.'},401); const b=await body(req); const niche=b.niche||'negócio local'; const business=b.business||'Minha Empresa'; if(!env.GEMINI_API_KEY){ return json({ok:false,error:'Gemini API não configurada no Cloudflare.'},400); }
 const prompt=`Crie uma landing page em JSON para ${business}, nicho ${niche}. Campos: headline, subtitle, benefits array, faq array com q/a, cta.`;
 const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${env.GEMINI_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}]})});
 const data=await res.json(); const text=data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
 return json({ok:true,text}); }
async function createProject(req, env){ const u=await requireUser(req, env); if(!u) return json({ok:false,error:'Não autenticado.'},401); const b=await body(req); const title=String(b.title||b.business||'Minha Página').trim(); const base=slugify(title); let slug=base; let i=1; while(await env.DB.prepare('SELECT id FROM projects WHERE slug=?').bind(slug).first()){ slug=`${base}-${++i}`; }
 const content={headline:b.headline||`Página profissional para ${title}`, subtitle:b.subtitle||'Criada com LumaPage AI', benefits:b.benefits||['Atendimento rápido','Design moderno','Mais vendas pelo WhatsApp'], faq:b.faq||[]};
 await env.DB.prepare('INSERT INTO projects(user_id,title,slug,niche,whatsapp,city,content_json,status) VALUES(?,?,?,?,?,?,?,?)').bind(u.id,title,slug,b.niche||'',b.whatsapp||'',b.city||'',JSON.stringify(content),'published').run(); return json({ok:true,slug,url:`/p/${slug}`}); }
async function publicProject(req, env, slug){ const p=await env.DB.prepare('SELECT * FROM projects WHERE slug=? AND status="published"').bind(slug).first(); if(!p) return json({ok:false,error:'Página não encontrada.'},404); await env.DB.prepare('UPDATE projects SET visits=visits+1 WHERE id=?').bind(p.id).run(); return json({ok:true,project:p,content:JSON.parse(p.content_json||'{}')}); }
async function clickWhatsapp(req, env, slug){ const p=await env.DB.prepare('SELECT id FROM projects WHERE slug=?').bind(slug).first(); if(p){ await env.DB.prepare('UPDATE projects SET whatsapp_clicks=whatsapp_clicks+1 WHERE id=?').bind(p.id).run(); } return json({ok:true}); }
async function pix(req, env){ const u=await requireUser(req, env); if(!u) return json({ok:false,error:'Não autenticado.'},401); const b=await body(req); const plan=await env.DB.prepare('SELECT * FROM plans WHERE slug=? AND active=1').bind(b.plan||'start').first(); if(!plan) return json({ok:false,error:'Plano inválido.'},400); if(!env.MERCADO_PAGO_ACCESS_TOKEN) return json({ok:false,error:'Mercado Pago não configurado.'},400);
 const payment={transaction_amount:Number(plan.price), description:`Plano ${plan.name} - LumaPage AI`, payment_method_id:'pix', payer:{email:u.email, first_name:u.name||'Cliente'}};
 const res=await fetch('https://api.mercadopago.com/v1/payments',{method:'POST',headers:{authorization:`Bearer ${env.MERCADO_PAGO_ACCESS_TOKEN}`,'content-type':'application/json','X-Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(payment)});
 const data=await res.json(); if(!res.ok) return json({ok:false,error:'Erro Mercado Pago',details:data},400);
 const qr=data?.point_of_interaction?.transaction_data?.qr_code_base64||''; const code=data?.point_of_interaction?.transaction_data?.qr_code||'';
 await env.DB.prepare('INSERT INTO payments(user_id,plan_id,mp_payment_id,amount,status,qr_code_base64,pix_code,raw_json) VALUES(?,?,?,?,?,?,?,?)').bind(u.id,plan.id,String(data.id),plan.price,data.status||'pending',qr,code,JSON.stringify(data)).run(); return json({ok:true,payment_id:data.id,status:data.status,qr_code_base64:qr,pix_code:code,amount:plan.price,plan:plan.name}); }
async function webhook(req, env){ const b=await body(req); const id=b?.data?.id || b?.id; if(!id || !env.MERCADO_PAGO_ACCESS_TOKEN) return json({ok:true}); const res=await fetch(`https://api.mercadopago.com/v1/payments/${id}`,{headers:{authorization:`Bearer ${env.MERCADO_PAGO_ACCESS_TOKEN}`}}); const data=await res.json(); const status=data.status||'unknown'; await env.DB.prepare('UPDATE payments SET status=?, raw_json=?, updated_at=? WHERE mp_payment_id=?').bind(status,JSON.stringify(data),now(),String(id)).run(); if(status==='approved'){ const p=await env.DB.prepare('SELECT * FROM payments WHERE mp_payment_id=?').bind(String(id)).first(); if(p){ await env.DB.prepare('UPDATE users SET plan_id=? WHERE id=?').bind(p.plan_id,p.user_id).run(); await env.DB.prepare('INSERT INTO subscriptions(user_id,plan_id,status,starts_at,expires_at,payment_id) VALUES(?,?,?,?,?,?)').bind(p.user_id,p.plan_id,'active',now(),now()+86400*30,String(id)).run(); }} return json({ok:true}); }
async function adminStats(req, env){ const a=await requireAdmin(req, env); if(!a) return json({ok:false,error:'Admin não autorizado.'},403); const users=await env.DB.prepare('SELECT COUNT(*) c FROM users').first(); const projects=await env.DB.prepare('SELECT COUNT(*) c FROM projects').first(); const paid=await env.DB.prepare('SELECT COALESCE(SUM(amount),0) total FROM payments WHERE status="approved"').first(); const logs=await env.DB.prepare('SELECT * FROM security_logs ORDER BY id DESC LIMIT 30').all(); return json({ok:true,stats:{users:users.c,projects:projects.c,revenue:paid.total},logs:logs.results||[]}); }
async function adminUsers(req, env){ const a=await requireAdmin(req, env); if(!a) return json({ok:false,error:'Admin não autorizado.'},403); const rows=await env.DB.prepare('SELECT id,name,email,phone,role,status,plan_id,created_at FROM users ORDER BY id DESC LIMIT 200').all(); return json({ok:true,users:rows.results||[]}); }
async function adminSettings(req, env){ const a=await requireAdmin(req, env); if(!a) return json({ok:false,error:'Admin não autorizado.'},403); if(req.method==='GET'){ const rows=await env.DB.prepare('SELECT key,value,private FROM settings ORDER BY key').all(); return json({ok:true,settings:rows.results||[]}); } const b=await body(req); for(const [k,v] of Object.entries(b||{})){ await env.DB.prepare('INSERT OR REPLACE INTO settings(key,value,private,updated_at) VALUES(?,?,0,?)').bind(k,String(v),now()).run(); } return json({ok:true}); }

export async function onRequest(context){ const {request, env, params}=context; if(!env.DB) return json({ok:false,error:'Binding DB não configurado no Cloudflare Pages.'},500); const url=new URL(request.url); const path='/' + (params.path||[]).join('/'); try{
  if(request.method==='OPTIONS') return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'content-type,authorization'}});
  if(path==='/health') return json({ok:true,time:now()});
  if(path==='/auth/register' && request.method==='POST') return register(request,env);
  if(path==='/auth/login' && request.method==='POST') return login(request,env);
  if(path==='/auth/me') return me(request,env);
  if(path==='/auth/forgot' && request.method==='POST') return forgot(request,env);
  if(path==='/auth/reset' && request.method==='POST') return resetPassword(request,env);
  if(path==='/plans') return plans(env);
  if(path==='/dashboard') return dashboard(request,env);
  if(path==='/ai/generate' && request.method==='POST') return aiGenerate(request,env);
  if(path==='/projects' && request.method==='POST') return createProject(request,env);
  if(path.startsWith('/public/')) return publicProject(request,env,path.split('/').pop());
  if(path.startsWith('/click/')) return clickWhatsapp(request,env,path.split('/').pop());
  if(path==='/payments/pix' && request.method==='POST') return pix(request,env);
  if(path==='/webhooks/mercadopago' && request.method==='POST') return webhook(request,env);
  if(path==='/admin/stats') return adminStats(request,env);
  if(path==='/admin/users') return adminUsers(request,env);
  if(path==='/admin/settings') return adminSettings(request,env);
  return json({ok:false,error:'Rota não encontrada',path},404);
 }catch(e){ return json({ok:false,error:'Erro interno',details:String(e?.message||e)},500); }}
